# Dockerfile
FROM openjdk:21-jdk-slim

# Copy your application JAR into the container
COPY target/restaurant-menu-service-0.0.1-SNAPSHOT.jar /app/app.jar

# Expose the port your app runs on
EXPOSE 8085

# Command to run your app
CMD ["java", "-jar", "/app/app.jar"]
